platform :ios,'10.0'

target 'CopyNews' do
   use_frameworks!
     pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'HandyJSON', '~>4.0.0-beta.1'
  pod 'Kingfisher'
  pod 'IBAnimatable'
  pod 'SwiftTheme'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SQLite.swift'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'SGPagingView'
  pod 'BMPlayer'
  pod 'FDFullscreenPopGesture'
  # pod 'Texture'
  pod 'lottie-ios'

end
